### ISSUE TITLE
can't recognize images of sanskrit text

### ISSUE THREAD

**Issue by hhihhio** [milind-prajapat/Devanagari-Character-Recognition#1]
![nilakantha-dharani](https://github.com/milind-prajapat/Devanagari-Character-Recognition/assets/97122860/ed2f2b9b-c1e6-4471-8e3e-4727e1290dd0)

**Comment by milind-prajapat** [comment]
Hello @maingocvinh. Sanskrit in currently not support by our deep learning models. We are only supporting hindi as of now. 
Image processing part of the repository should be able to segment most of these characters though. You can make use of it, if it works for you.
Thank you
